apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-rear-deployment
  labels:
    app: poc_rear
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc-rear
  template:
    metadata:
      labels:
        app: poc-rear
    spec:
      containers:
      - name: poc-rear-bin 
        image: pitoniak32/test_poc_rear:0.0.1
        env:
        - name: RUST_LOG
          value: "INFO"
        - name: DEV_MODE
          value: "true"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
