apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-rear-deployment
  namespace: default
  labels:
    app: poc-rear
spec:
  replicas: 4
  selector:
    matchLabels:
      app: poc-rear
  template:
    metadata:
      labels:
        app: poc-rear
    spec:
      containers:
      - name: poc-rear-bin 
        image: pitoniak32/test_poc_rear:0.0.1
        env:
        - name: RUST_LOG
          value: "INFO"
        - name: DEV_MODE
          value: "true"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017"
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: poc-rear 
  namespace: default
spec:
  type: NodePort
  selector:
    app: poc-rear
  ports:
    - name: tcp-port
      protocol: TCP
      port: 8080
      targetPort: 8080
