apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
